### ISSUE TITLE
Assignments

### ISSUE THREAD

**Issue by tjusticelee** [ScottJohnson02/tsct-portal#39]
- If assignment details on students has too many characters there will be a 502 error
- Assignments can be changed with file path. /assignments/n/x
(n) can be changed to show a different assignment page
- Cannot give students 0 points
-Was able to leave some fields blank for assignments. Furthermore, having blank fields will not allow the teacher to give points for the assignments.
- A teacher cannot enter all the grades in one shot

**Comment by CodeMart10** [comment]
Fixed issue, thanks j
